# IMPORTANT: This file is generated by cucumber-rails - edit at your own peril.
# It is recommended to regenerate this file in the future when you upgrade to a
# newer version of cucumber-rails. Consider adding your own code to a new file
# instead of editing this one. Cucumber will automatically load all features/**/*.rb
# files.

ENV["GEMINI_API_KEY"] ||= "test-placeholder"

require "cucumber/rails"
require "webmock/cucumber"
require "factory_bot_rails"
require "rspec/mocks"
require "active_job/test_helper"

# Raise on uncaught exceptions so scenarios fail loudly.
ActionController::Base.allow_rescue = false

# Block real network calls — step definitions stub what they need.
WebMock.disable_net_connect!(allow_localhost: true)

# FactoryBot DSL (create, build, etc.) available in step definitions.
World(FactoryBot::Syntax::Methods)

# RSpec mocks (allow, allow_any_instance_of, expect().to receive, etc.)
World(RSpec::Mocks::ExampleMethods)

# ActiveJob test helpers (perform_enqueued_jobs)
World(ActiveJob::TestHelper)

# Treat all image URLs as reachable by default (mirrors test_helper.rb).
Before do
  RSpec::Mocks.setup
  allow(ImageReachability).to receive(:reachable) { |urls| urls.to_a } if defined?(ImageReachability)
end

After do
  RSpec::Mocks.teardown
end

# DatabaseCleaner — use transaction strategy (fast); switch to truncation for
# @javascript scenarios (Capybara with a real browser runs in a separate thread).
begin
  DatabaseCleaner.strategy = :transaction
rescue NameError
  raise "Add database_cleaner-active_record to your Gemfile :test group."
end

Before("@javascript") do
  DatabaseCleaner.strategy = :truncation
end

After("@javascript") do
  DatabaseCleaner.strategy = :transaction
end

Cucumber::Rails::Database.javascript_strategy = :truncation

# Sign-in helper for Cucumber step definitions using Rack::Test.
module CucumberAuthHelpers
  def sign_in_as(user, password = "password123")
    page.driver.post(session_url, login: user.email_address, password: password)
  end
end

World(CucumberAuthHelpers)
