FactoryBot.define do
  factory :challenge do
    association :challenger, factory: :user
    # image_set is optional on Challenge (nil = uses system default)
    image_set { nil }

    # token is auto-generated by Challenge#generate_token before_create

    trait :with_image_set do
      association :image_set
    end
  end
end
