FactoryBot.define do
  factory :match do
    association :host, factory: :user
    association :image_set
    rounds_total { 3 }
    seconds_per_round { 30 }
    status { "lobby" }

    # code is auto-generated by Match#ensure_code before_validation

    trait :active do
      status { "active" }
      started_at { 1.minute.ago }
    end

    trait :finished do
      status { "finished" }
      started_at { 10.minutes.ago }
      finished_at { Time.current }
    end
  end
end
