require "rails_helper"

RSpec.describe Match, type: :model do
  subject(:match) { build(:match) }

  # ── Validations ──────────────────────────────────────────────────────────────

  describe "validations" do
    it "is valid with default factory attributes" do
      expect(match).to be_valid
    end

    it "requires a code" do
      match.code = nil
      match.valid?
      # code is auto-generated by ensure_code before_validation, so nil is patched
      expect(match.code).to be_present
    end

    it "rejects duplicate codes" do
      existing = create(:match)
      duplicate = build(:match, code: existing.code)
      expect(duplicate).not_to be_valid
      expect(duplicate.errors[:code]).to be_present
    end

    it "rejects an invalid status" do
      match.status = "unknown"
      expect(match).not_to be_valid
      expect(match.errors[:status]).to be_present
    end

    it "accepts all valid statuses" do
      Match::STATUSES.each do |s|
        match.status = s
        expect(match).to be_valid, "expected status '#{s}' to be valid"
      end
    end

    it "requires rounds_total to be a positive integer" do
      match.rounds_total = 0
      expect(match).not_to be_valid
    end

    it "requires seconds_per_round to be a positive integer" do
      match.seconds_per_round = 0
      expect(match).not_to be_valid
    end
  end

  # ── Code generation ──────────────────────────────────────────────────────────

  describe ".generate_unique_code" do
    it "returns a 6-character string from the Crockford alphabet" do
      code = Match.generate_unique_code
      expect(code.length).to eq(Match::CODE_LENGTH)
      expect(code.chars).to all(satisfy { |c| Match::CODE_ALPHABET.include?(c) })
    end

    it "does not produce ambiguous characters (0, O, 1, I)" do
      100.times do
        code = Match.generate_unique_code
        expect(code.match?(/[01IO]/)).to be false
      end
    end
  end

  # ── Predicate helpers ─────────────────────────────────────────────────────────

  describe "#host?" do
    let(:host) { create(:user) }
    let(:other) { create(:user) }
    let(:match) { create(:match, host: host) }

    it "returns true for the host user" do
      expect(match.host?(host)).to be true
    end

    it "returns false for another user" do
      expect(match.host?(other)).to be false
    end

    it "returns false for nil" do
      expect(match.host?(nil)).to be_falsy
    end
  end

  describe "#joined_by?" do
    let(:user) { create(:user) }
    let(:match) { create(:match) }

    it "returns false when the user has no MatchPlayer row" do
      expect(match.joined_by?(user)).to be false
    end

    it "returns true when the user has a MatchPlayer row" do
      create(:match_player, match: match, user: user)
      expect(match.joined_by?(user)).to be true
    end

    it "returns false for nil user" do
      expect(match.joined_by?(nil)).to be_falsy
    end
  end

  describe "#joinable_by?" do
    let(:user) { create(:user) }

    it "returns false for nil user" do
      match = create(:match)
      expect(match.joinable_by?(nil)).to be false
    end

    it "returns false when the match is active" do
      match = create(:match, :active)
      expect(match.joinable_by?(user)).to be false
    end

    it "returns false when the match is finished" do
      match = create(:match, :finished)
      expect(match.joinable_by?(user)).to be false
    end

    it "returns true for a lobby match under capacity" do
      match = create(:match)
      expect(match.joinable_by?(user)).to be true
    end

    it "returns true even if at capacity when the user already joined" do
      match = create(:match)
      create(:match_player, match: match, user: user)
      # Fake capacity by stubbing
      allow(match).to receive(:at_capacity?).and_return(true)
      expect(match.joinable_by?(user)).to be true
    end

    it "returns false when at capacity and user has not joined" do
      match = create(:match)
      allow(match).to receive(:at_capacity?).and_return(true)
      expect(match.joinable_by?(user)).to be false
    end
  end

  describe "#startable_by?" do
    let(:host) { create(:user) }
    let(:other) { create(:user) }
    let(:match) { create(:match, host: host) }

    before { create(:match_player, match: match, user: host) }

    it "returns true for the host of a lobby match with at least one player" do
      expect(match.startable_by?(host)).to be true
    end

    it "returns false for a non-host user" do
      expect(match.startable_by?(other)).to be false
    end

    it "returns false when match is already active" do
      match.update!(status: "active", started_at: Time.current)
      expect(match.startable_by?(host)).to be false
    end
  end

  describe "#at_capacity?" do
    it "returns false when player count is below the cap" do
      match = create(:match)
      expect(match.at_capacity?).to be false
    end

    it "returns true when player count equals LOBBY_CAPACITY" do
      match = create(:match)
      allow(match.match_players).to receive(:count).and_return(Match::LOBBY_CAPACITY)
      expect(match.at_capacity?).to be true
    end
  end

  describe "#current_round" do
    it "returns nil when there are no rounds" do
      match = create(:match, :active)
      expect(match.current_round).to be_nil
    end

    it "returns the last round by insertion order" do
      match = create(:match, :active)
      image = create(:image)
      r1 = create(:match_round, match: match, index: 1, image: image)
      r2 = create(:match_round, match: match, index: 2, image: image)
      expect(match.current_round).to eq(r2)
      expect(match.current_round).not_to eq(r1)
    end
  end

  describe "#to_param" do
    it "returns the code" do
      match = build(:match, code: "ABC123")
      expect(match.to_param).to eq("ABC123")
    end
  end

  # ── Scopes ───────────────────────────────────────────────────────────────────

  describe "scopes" do
    it ".lobby returns only lobby matches" do
      lobby  = create(:match)
      active = create(:match, :active)
      expect(Match.lobby).to include(lobby)
      expect(Match.lobby).not_to include(active)
    end

    it ".active returns only active matches" do
      lobby  = create(:match)
      active = create(:match, :active)
      expect(Match.active).to include(active)
      expect(Match.active).not_to include(lobby)
    end

    it ".finished returns only finished matches" do
      finished = create(:match, :finished)
      lobby    = create(:match)
      expect(Match.finished).to include(finished)
      expect(Match.finished).not_to include(lobby)
    end
  end
end
